'use client';
import { useEffect, useState } from 'react';
import { useRouter } from 'next/navigation';
import { supabase } from '../../lib/supabase';

type Product={id:number;name:string;price:number;category:string;image_url:string;description:string;in_stock:boolean};
const ADMIN_EMAIL='bolaandolusegun16@gmail.com';
const BUCKET='products';

export default function AdminPage(){
 const router=useRouter(); const [authorized,setAuthorized]=useState(false); const [name,setName]=useState(''); const [price,setPrice]=useState(''); const [category,setCategory]=useState(''); const [image,setImage]=useState(''); const [description,setDescription]=useState(''); const [inStock,setInStock]=useState(true); const [file,setFile]=useState<File|null>(null); const [loading,setLoading]=useState(false); const [products,setProducts]=useState<Product[]>([]); const [editingId,setEditingId]=useState<number|null>(null); const [openMenuId,setOpenMenuId]=useState<number|null>(null);
 useEffect(()=>{checkAdmin()},[]);
 async function checkAdmin(){const {data:{user}}=await supabase.auth.getUser();if(!user||user.email?.toLowerCase()!==ADMIN_EMAIL){router.replace('/admin/login');return;}setAuthorized(true);fetchProducts();}
 async function fetchProducts(){const {data}=await supabase.from('products').select('*').order('id',{ascending:false});setProducts(data||[]);}
 function resetForm(){setName('');setPrice('');setCategory('');setImage('');setDescription('');setInStock(true);setFile(null);setEditingId(null);}
 async function uploadImage(){if(!file)return image;if(!file.type.startsWith('image/'))throw new Error('Please choose an image file.');if(file.size>5*1024*1024)throw new Error('Image must be smaller than 5MB.');const ext=file.name.split('.').pop()?.toLowerCase()||'jpg';const path=`${Date.now()}-${crypto.randomUUID()}.${ext}`;const {error}=await supabase.storage.from(BUCKET).upload(path,file,{upsert:false,contentType:file.type});if(error)throw error;return supabase.storage.from(BUCKET).getPublicUrl(path).data.publicUrl;}
 async function saveProduct(){if(!name.trim()||!price||!category.trim()){alert('Please fill product name, price, and category.');return;}setLoading(true);try{const imageUrl=await uploadImage();const payload={name:name.trim(),price:Number(price),category:category.trim(),image_url:imageUrl,description:description.trim(),in_stock:inStock};let error;if(editingId!==null){({error}=await supabase.from('products').update(payload).eq('id',editingId));}else{({error}=await supabase.from('products').insert([payload]));}if(error)throw error;resetForm();await fetchProducts();}catch(e:any){alert(e.message||'Could not save product.');}finally{setLoading(false);}}
 function startEdit(p:Product){setName(p.name);setPrice(String(p.price));setCategory(p.category);setImage(p.image_url||'');setDescription(p.description||'');setInStock(p.in_stock);setFile(null);setEditingId(p.id);setOpenMenuId(null);scrollTo({top:0,behavior:'smooth'});}
 async function deleteProduct(id:number){if(!confirm('Delete this product?'))return;const {error}=await supabase.from('products').delete().eq('id',id);if(error){alert(error.message);return;}setOpenMenuId(null);if(editingId===id)resetForm();fetchProducts();}
 async function toggleStock(p:Product){const {error}=await supabase.from('products').update({in_stock:!p.in_stock}).eq('id',p.id);if(error)alert(error.message);else fetchProducts();}
 async function signOut(){await supabase.auth.signOut();router.replace('/admin/login');}
 if(!authorized)return <main style={{padding:40,textAlign:'center'}}>Checking admin access...</main>;
 return <main style={{minHeight:'100vh',background:'#fffaf5',padding:20,maxWidth:1050,margin:'0 auto',fontFamily:'Arial,sans-serif',color:'#241a1c'}}>
  <header style={{display:'flex',justifyContent:'space-between',alignItems:'center',gap:12,marginBottom:22}}><div><p style={{color:'#8b1530',letterSpacing:2,fontSize:11,fontWeight:700}}>FLORAL ACCESSORIES</p><h1 style={{margin:'0 0 4px',fontFamily:'Georgia,serif'}}>Product Dashboard</h1><p style={{margin:0,color:'#6b7280'}}>Manage your store without coding.</p></div><button onClick={signOut} style={secondary}>Sign out</button></header>
  <section style={card}><h2 style={{marginTop:0}}>{editingId!==null?'Edit Product':'Add Product'}</h2><input placeholder="Product name" value={name} onChange={e=>setName(e.target.value)} style={input}/><input placeholder="Price (₦)" inputMode="numeric" value={price} onChange={e=>setPrice(e.target.value)} style={input}/><input placeholder="Category (Jewelry, Perfumes...)" value={category} onChange={e=>setCategory(e.target.value)} style={input}/><label style={{display:'block',fontSize:13,fontWeight:700,marginBottom:12}}>Product photo<input type="file" accept="image/*" onChange={e=>setFile(e.target.files?.[0]||null)} style={{display:'block',marginTop:7,width:'100%'}}/></label>{image&&!file&&<img src={image} alt="Current product" style={{width:90,height:90,objectFit:'cover',borderRadius:12,marginBottom:12}}/>}<textarea placeholder="Description" value={description} onChange={e=>setDescription(e.target.value)} style={{...input,height:100}}/><label style={{display:'flex',alignItems:'center',gap:8,marginBottom:16}}><input type="checkbox" checked={inStock} onChange={e=>setInStock(e.target.checked)}/> In stock</label><button onClick={saveProduct} disabled={loading} style={primary}>{loading?'Saving...':editingId!==null?'Update Product':'Add Product'}</button>{editingId!==null&&<button onClick={resetForm} style={{...secondary,marginLeft:10}}>Cancel</button>}</section>
  <h2>All Products</h2><div style={{display:'grid',gap:14}}>{products.map(p=><div key={p.id} style={productCard}><img src={p.image_url||'https://images.unsplash.com/photo-1617038260897-41a1f14a8ca0?auto=format&fit=crop&w=300&q=80'} alt={p.name} style={{width:82,height:82,objectFit:'cover',borderRadius:12}}/><div style={{flex:1}}><b>{p.name}</b><div style={{color:'#8b1530',fontWeight:700}}>₦{Number(p.price).toLocaleString()}</div><small>{p.category} · {p.in_stock?'In stock':'Sold out'}</small></div><button onClick={()=>toggleStock(p)} style={secondary}>{p.in_stock?'Mark sold out':'Mark in stock'}</button><button onClick={()=>setOpenMenuId(openMenuId===p.id?null:p.id)} style={{border:0,background:'transparent',fontSize:24,cursor:'pointer'}}>⋮</button>{openMenuId===p.id&&<div style={menuBox}><button onClick={()=>startEdit(p)} style={menu}>Edit</button><button onClick={()=>deleteProduct(p.id)} style={{...menu,color:'#b00020'}}>Delete</button></div>}</div>)}</div>
 </main>;
}
const input:React.CSSProperties={width:'100%',boxSizing:'border-box',padding:13,marginBottom:12,border:'1px solid #d1d5db',borderRadius:10,fontSize:15};
const card:React.CSSProperties={background:'white',border:'1px solid #eadfd7',borderRadius:18,padding:20,boxShadow:'0 6px 20px rgba(0,0,0,.04)',marginBottom:28};
const productCard:React.CSSProperties={border:'1px solid #e5e7eb',borderRadius:16,padding:14,display:'flex',gap:14,alignItems:'center',background:'white',position:'relative',flexWrap:'wrap'};
const primary:React.CSSProperties={padding:'12px 18px',border:0,borderRadius:10,background:'#5a0712',color:'white',fontWeight:700,cursor:'pointer'};
const secondary:React.CSSProperties={padding:'10px 14px',border:'1px solid #ddd',borderRadius:10,background:'white',cursor:'pointer'};
const menuBox:React.CSSProperties={position:'absolute',right:12,top:55,background:'white',border:'1px solid #ddd',borderRadius:10,boxShadow:'0 8px 20px rgba(0,0,0,.12)',padding:6,zIndex:2};
const menu:React.CSSProperties={display:'block',width:'100%',border:0,background:'white',padding:'9px 14px',textAlign:'left',cursor:'pointer'};
