const fs = require('fs');
const path = require('path');
const file = path.join(process.cwd(), 'app', 'page.tsx');
let s = fs.readFileSync(file, 'utf8');

if (!s.includes('FLORAL_CHAT_ASSISTANT')) {
  s = s.replace(
    "[open,setOpen]=useState(false),[payment,setPayment]=useState(false),[loading,setLoading]=useState(true),[copied,setCopied]=useState(false),[welcome,setWelcome]=useState(true);",
    "[open,setOpen]=useState(false),[payment,setPayment]=useState(false),[loading,setLoading]=useState(true),[copied,setCopied]=useState(false),[welcome,setWelcome]=useState(true),[chatOpen,setChatOpen]=useState(false),[chatInput,setChatInput]=useState(''),[chatMessages,setChatMessages]=useState<{from:'bot'|'user',text:string}[]>([{from:'bot',text:'Hi 👋🏽 Welcome to Floral Accessories! How can I help you today?'}]);"
  );

  s = s.replace(
    "const sendPaidOrder=()=>wa(`Hello Floral Accessories Store, I have made payment for my order.",
    "const sendChat=()=>{const q=chatInput.trim();if(!q)return;const low=q.toLowerCase();let reply='I can help with jewelry, perfumes, your cart, payment, delivery, or product recommendations. 💕';if(low.includes('jewelry')||low.includes('jewellery'))reply='Absolutely! 💎 Tap Shop Now or choose a jewelry category to browse our pieces.';else if(low.includes('perfume'))reply='Yes! 🌸 We have perfumes available. Tap Perfumes to see what is currently in stock.';else if(low.includes('cart')||low.includes('bag'))reply=cart.length?'You have '+cart.reduce((a,i)=>a+i.quantity,0)+' item(s) in your bag. Open your bag to continue checkout. 🛍️':'Your bag is empty right now. Tap Shop Now and add something beautiful. 💕';else if(low.includes('payment')||low.includes('account')||low.includes('pay'))reply='Payment is by bank transfer to '+BANK.name+'. Account: '+BANK.accountNumber+'. You can copy the account number from checkout.';else if(low.includes('delivery')||low.includes('deliver'))reply='🚚 Delivery is available. Tell us your delivery location on WhatsApp and we will confirm the delivery details for you.';else if(low.includes('gift')||low.includes('recommend'))reply='🎁 I would love to help! For a gift, browse our jewelry and perfumes, or tell me the person, occasion and budget.';else if(low.includes('under')||low.includes('price')||low.includes('₦')){const matches=products.filter(p=>p.name.toLowerCase().includes(low.replace(/under|price|₦|ngn|naira|[0-9,]+/g,'').trim())).slice(0,3);reply=matches.length?'I found '+matches.length+' matching product(s): '+matches.map(p=>p.name+' — '+money(p.price)).join(', ')+'. 💎':'Tell me the product name or your budget and I will help you find a match.';}setChatMessages(m=>[...m,{from:'user',text:q},{from:'bot',text:reply}]);setChatInput('')};\n const sendPaidOrder=()=>wa(`Hello Floral Accessories Store, I have made payment for my order."
  );

  const chatStyles = `@keyframes faChatIn{from{opacity:0;transform:translateY(12px) scale(.97)}to{opacity:1;transform:translateY(0) scale(1)}}.fa-chat-panel{position:fixed;right:18px;bottom:86px;width:min(365px,calc(100vw - 24px));height:min(570px,calc(100vh - 110px));z-index:60;background:#fff;border:1px solid #eadbd5;border-radius:22px;box-shadow:0 20px 60px rgba(45,20,25,.22);display:flex;flex-direction:column;overflow:hidden;animation:faChatIn .25s ease-out}.fa-chat-head{padding:16px 18px;background:#6e1f2b;color:#fff;display:flex;align-items:center;justify-content:space-between}.fa-chat-head strong{font-size:16px}.fa-chat-head small{display:block;opacity:.82;margin-top:2px}.fa-chat-x{border:0;background:rgba(255,255,255,.15);color:#fff;width:32px;height:32px;border-radius:50%;font-size:20px;cursor:pointer}.fa-chat-body{padding:14px;overflow:auto;flex:1;background:#fffaf8}.fa-chat-msg{max-width:84%;padding:10px 12px;border-radius:15px;margin:7px 0;font-size:13px;line-height:1.4;white-space:pre-wrap}.fa-chat-bot{background:#f4e9e6;color:#32151b;margin-right:auto}.fa-chat-user{background:#6e1f2b;color:#fff;margin-left:auto}.fa-chat-quick{display:flex;gap:7px;flex-wrap:wrap;padding:9px 12px;border-top:1px solid #eee1dd;background:#fff}.fa-chat-quick button{border:1px solid #dcc5bf;background:#fff;border-radius:999px;padding:7px 10px;color:#6e1f2b;font-weight:700;font-size:11px;cursor:pointer}.fa-chat-form{display:flex;gap:7px;padding:11px;border-top:1px solid #eadbd5;background:#fff}.fa-chat-input{flex:1;border:1px solid #d9c5c0;border-radius:12px;padding:11px;outline:none;font-size:13px}.fa-chat-send{border:0;border-radius:12px;padding:0 15px;background:#6e1f2b;color:#fff;font-weight:800;cursor:pointer}.fa-chat-launch{position:fixed;right:18px;bottom:18px;z-index:59;border:0;border-radius:999px;background:#6e1f2b;color:#fff;padding:13px 17px;box-shadow:0 12px 28px rgba(45,20,25,.25);font-weight:800;cursor:pointer}.fa-chat-launch span{margin-left:6px}@media(max-width:700px){.fa-chat-launch{right:12px;bottom:12px;padding:12px 14px}.fa-chat-panel{right:12px;bottom:72px;width:calc(100vw - 24px);height:min(560px,calc(100vh - 88px))}}`;
  s = s.replace("<style jsx global>{`", "<style jsx global>{`" + chatStyles);

  const chatMarkup = `<!-- FLORAL_CHAT_ASSISTANT --><button className="fa-chat-launch" aria-label="Open Floral Accessories chat" onClick={()=>setChatOpen(v=>!v)}>💬<span>Chat with us</span></button>{chatOpen&&<div className="fa-chat-panel" role="dialog" aria-label="Floral Accessories chat"><div className="fa-chat-head"><div><strong>Floral Accessories Assistant 💕</strong><small>Here to help you shop</small></div><button className="fa-chat-x" onClick={()=>setChatOpen(false)} aria-label="Close chat">×</button></div><div className="fa-chat-body">{chatMessages.map((m,i)=><div key={i} className={'fa-chat-msg '+(m.from==='bot'?'fa-chat-bot':'fa-chat-user')}>{m.text}</div>)}</div><div className="fa-chat-quick"><button onClick={()=>{setChatMessages(m=>[...m,{from:'user',text:'🛍️ Shop now'},{from:'bot',text:'Great! Scroll up and browse our collections. I can also help you find something specific. 💕'}])}}>🛍️ Shop now</button><button onClick={()=>{setChatMessages(m=>[...m,{from:'user',text:'💎 Jewelry'},{from:'bot',text:'Our jewelry collection is ready for you. Tell me a style or budget and I can help.'}])}}>💎 Jewelry</button><button onClick={()=>{setChatMessages(m=>[...m,{from:'user',text:'🌸 Perfumes'},{from:'bot',text:'Browse our perfume collection above. Ask me for recommendations too!'}])}}>🌸 Perfumes</button><button onClick={()=>{setChatMessages(m=>[...m,{from:'user',text:'🛍️ My cart'},{from:'bot',text:cart.length?'You have '+cart.reduce((a,i)=>a+i.quantity,0)+' item(s) in your bag.':'Your bag is empty right now.'}]);setOpen(true)}}>🛍️ My cart</button><button onClick={()=>{setPayment(true);setChatMessages(m=>[...m,{from:'user',text:'💳 Payment information'},{from:'bot',text:'Transfer to '+BANK.name+', '+BANK.accountName+', account '+BANK.accountNumber+'. The checkout has a Copy button too.'}])}}>💳 Payment</button><button onClick={()=>wa('Hello Floral Accessories, I need help with my order.')}>👩🏽‍💼 Talk to us</button><button onClick={()=>wa('Hello Floral Accessories, please help me with delivery for my order.')}>🚚 Delivery</button><button onClick={()=>setChatMessages(m=>[...m,{from:'bot',text:'🎁 Gift idea: tell me who the gift is for, the occasion and your budget, and I will suggest something lovely.'}])}>🎁 Gift ideas</button></div><form className="fa-chat-form" onSubmit={e=>{e.preventDefault();sendChat()}}><input className="fa-chat-input" value={chatInput} onChange={e=>setChatInput(e.target.value)} placeholder="Ask about products, prices, delivery..."/><button className="fa-chat-send" type="submit">Send</button></form></div>}`;
  s = s.replace(" </main>;", ` ${chatMarkup}\n </main>;`);
}

fs.writeFileSync(file, s);
console.log('Floral Accessories chat assistant applied.');
